### ISSUE TITLE
Validate fails regression test on issue 308

### ISSUE THREAD

**Issue by jpl-jengelke** [NASA-PDS-Incubator/validate#547]
## 🐛 Describe the bug identified during I&T
Regression test [validate#308](https://github.com/NASA-PDS/validate/issues/308) fails in the regression testing tool. 

**Posted here for discussion or to address root cause.** It appears that test data is no longer valid for the validate tool. Perhaps the tool evolved to report problems with the data set that were unrecognized at the time the issue was originally created. 

Data set fails with 
```
error.table.bad_field_read
```
e.g.
```
ERROR  [error.table.bad_field_read]   line 0: null
```
and does not contain 
```
WARNING  [warning.integrity.unreferenced_member]   Identifier 'urn:nasa:pds:mess-rs-raw:data.odf:mess_rs_07155_156_60s_odf::1.0
```
Perhaps the validation report changed or certain checks no longer process after subsequent issues were addressed in the tool. It's also possible the data set isn't clean and fails tests created after this ticket. 

## 🥼 Related Test Case(s)
B12.0, VAL.2

## 🔁 : Related issues
https://github.com/NASA-PDS/validate/issues/308

---

## ➕ Additional Details
https://pds-jenkins.jpl.nasa.gov/job/console-regression-tests/job/develop/298/console
https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/4058181

### 📜 To Reproduce
See steps [here](https://pds-jenkins.jpl.nasa.gov/job/console-regression-tests/job/develop/298/console).

### 🕵️ Expected behavior
Test passes all stages successfully.

### 📚 Version of Software Used
Validate 3.0.2

### 🩺 Test Data / Additional context
Test data located at https://github.com/NASA-PDS/validate/tree/main/src/test/resources/github308

### 🖥 System Info
 - OS: Mac OS X 11.7.1 or Ubuntu-latest (Dockerized)
 - java 11.0.3 2019-04-16 LTS
 - Validate 2.4.0 or 3.0.0
 - GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
 
---

**Comment by tloubrieu-jpl** [comment]
Could be corrected with https://github.com/NASA-PDS/validate/issues/544

@jpl-jengelke will retest that.

**Comment by viviant100** [comment]
Jenkin regression tests still fail, but [validate#308](https://github.com/NASA-PDS/validate/issues/308) now has 2/3 executions passing instead of only 1/3. No change in [validate#303](https://github.com/NASA-PDS/validate/issues/303).  Testrail result in https://cae-testrail.jpl.nasa.gov/testrail/index.php?/runs/view/18818&group_by=cases:section_id&group_order=asc.

**Comment by jordanpadams** [comment]
@jpl-jengelke @viviant100 we may need to update this issue template, but can you provide some more details here?

* Actual result
* Expected result
* Test data

I see some of this info in the test rail logs, but it is a bit of a dig to get there. I also unfortunately do not know what this test data file is and how it is failing `/data/jenkins/workspace/console-regression-tests_develop/datasets/validate/303/testdata/val303a.xml`

**Comment by jordanpadams** [comment]
additionally, adding `needs:triage` back to the ticket until we better understand the issue and can triage the severity of the ticket.

@tloubrieu-jpl can we make sure in the future that we either keep the `needs:triage` label on the ticket until we assign a severity? this will also help with the RDD generation so it doesn't show up as "unknown" severity. it will also make sure we catch any highs/criticals that could potentially be show stoppers for the build delivery.

**Comment by jordanpadams** [comment]
additionally, adding `needs:triage` back to the ticket until we better understand the issue and can triage the severity of the ticket.

@tloubrieu-jpl can we make sure in the future that we either keep the `needs:triage` label on the ticket until we assign a severity? this will also help with the RDD generation so it doesn't show up as "unknown" severity. it will also make sure we catch any highs/criticals that could potentially be show stoppers for the build delivery.

**Comment by jordanpadams** [comment]
@jpl-jengelke I take it back. it looks like the one that failed was `/data/jenkins/workspace/console-regression-tests_develop/datasets/validate/303/testdata/val303b.xml` which is the file that Richard attached to the original ticket. will need to update functionality to handle this. tightly coupled to #548

**Comment by nutjob4life** [comment]
I cannot access results in cae-testrail; I don't think I'm provisioned to have access there.

<img width="339" alt="Results of login attempts with JPL credentials to CAE-testrail" src="https://user-images.githubusercontent.com/814813/202310950-4c0a324a-bee1-4710-9c19-7bca0453944d.png">

@viviant100 @jpl-jengelke is it possible to include the data in https://cae-testrail.jpl.nasa.gov/testrail/index.php?/runs/view/18818&group_by=cases:section_id&group_order=asc in a comment on this issue?

(Or better yet, a command-line sequence I can run that reproduces it? 😄)

**Comment by nutjob4life** [comment]
Incidentally, I tried validate-2.3.0 on the following XML files in `src/test/resources/github308/invalid`:

- `data_spectra/kgrs_calibrated_spectra_per1.xml`
- `data_spectra/spectra_data_collection_inventory.xml`
- `document/pccref.xml`
- `VALID_odf07155_msgr_11.xml`
- `bundle_kaguya_derived.xml`

by running `validate-2.3.0/bin/validate FILE` on each. Each one produced:
```
Summary:

  0 error(s)
  0 warning(s)

  Product Validation Summary:
    1          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
```
and none of them produced

    WARNING  [warning.integrity.unreferenced_member]   

so maybe I'm using the wrong files or the wrong command-line arguments? 

For fun I tried the XML files under `valid` too … same result 🤷‍♀️  … and validate-3.0.2 … same result 🧐

**Comment by jpl-jengelke** [comment]
@nutjob4life My experience is that CAE Testrail access must be provisioned separately by CAE for affiliates. The data there is no different from PDS Jenkins as it's reported from PDS Jenkins. If you're seeking an older manual test case result, I will see if we can grab it and paste it in an email. 

My results from `validate` 2.3.0 differ. 
command:
```
validate-2.3.0/bin/validate  -R pds4.bundle -t /sourcecode/source/pds/validate/src/test/resources/github308/valid/
...
java --version
java 11.0.3 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)
...
validate-2.3.0/bin/validate --version

gov.nasa.pds:validate
Version 2.3.0
Release Date: 2022-07-25 22:27:49

Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.
```
results:
```
Summary:

  0 error(s)
  3 warning(s)

  Product Validation Summary:
    5          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    6          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    2            warning.integrity.unreferenced_member
    1            warning.integrity.pds4_version_mismatch
```
I'm using data sets in the src/test/resources directory of the latest validate and/or data sets reported during the ticket creation as having the issue and/or data sets reported by the developer in the comments.

We should talk to see why we're getting seemingly different results.

**Comment by jpl-jengelke** [comment]
It turns out that the test failure referenced in the [Build 12.0 System Test report (.pdf)](https://pds-engineering.jpl.nasa.gov/sites/default/files/documents/Build%20Deliverables/Build%2012.0%20I%26T%20Deilverables/build12.0testProcs.pdf) was addressed by opening issue #432 and referenced again in PR #440. The fix was slated for B13.0 but does not appear to be ready nor closed. As issue #432 is not marked as a `requirement`, I have removed this portion of the test from the regression tests to yield a `PASS`. 

I also do not see the `error.table.bad_field_read` anymore, so this is clean to close.
